name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker build -t tinumistry/cropycicd001:1.0 .
      env:
        DOCKER_CLI_AGGREGATE: 1

    - name: Log in to Docker
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD  }}
        docker push tinumistry/cropycicd001:1.0 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_CICD }} '
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: crdemo-cicd
          region: us-central1
          image: docker.io/tinumistry/cropycicd001:1.0
          flags: ' --allow-unauthenticated '
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }} 
      
